# .github/release.yml
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - ignore-for-release
      - no-changelog
    authors:
      - pre-commit-ci
  categories:
    - title: Training
      labels:
        - training
    - title: Models
      labels:
        - models
    - title: Graphs
      labels:
        - graphs
    - title: Other Changes
      labels:
        - "*"
