activation: GELU
num_channels: 1024

model:
  _target_: anemoi.models.models.encoder_processor_decoder.AnemoiModelEncProcDec

processor:
  _target_: anemoi.models.layers.processor.GraphTransformerProcessor
  _convert_: all
  activation: ${model.activation}
  trainable_size: ${model.trainable_parameters.hidden2hidden}
  sub_graph_edge_attributes: ${model.attributes.edges}
  num_layers: 16
  num_chunks: 2
  mlp_hidden_ratio: 4 # GraphTransformer or Transformer only
  num_heads: 16 # GraphTransformer or Transformer only
  dropout_p: 0.0 # GraphTransformer or Transformer only

encoder:
  _target_: anemoi.models.layers.mapper.GraphTransformerForwardMapper
  _convert_: all
  trainable_size: ${model.trainable_parameters.data2hidden}
  sub_graph_edge_attributes: ${model.attributes.edges}
  activation: ${model.activation}
  num_chunks: 1
  mlp_hidden_ratio: 4 # GraphTransformer or Transformer only
  num_heads: 16 # GraphTransformer or Transformer only

decoder:
  _target_: anemoi.models.layers.mapper.GraphTransformerBackwardMapper
  _convert_: all
  trainable_size: ${model.trainable_parameters.hidden2data}
  sub_graph_edge_attributes: ${model.attributes.edges}
  activation: ${model.activation}
  num_chunks: 1
  mlp_hidden_ratio: 4 # GraphTransformer or Transformer only
  num_heads: 16 # GraphTransformer or Transformer only

trainable_parameters:
  data: 8
  hidden: 8
  data2hidden: 8
  hidden2data: 8
  hidden2hidden: 8 # GNN and GraphTransformer Processor only


attributes:
  edges:
  - edge_length
  - edge_dirs
  nodes: []

node_loss_weight: area_weight

# Bounding configuration
# bounding: #These are applied in order
#   - _target_: anemoi.models.layers.bounding.ReluBounding #[0, infinity)
#     variables:
#     - tp
#   - _target_: anemoi.models.layers.bounding.FractionBounding # fraction of tp
#     variables:
#     - cp
#     min_val: 0
#     max_val: 1
#     total_var: tp
